### ISSUE TITLE
Would it be psosible to update addon to support ingress instead of port ?

### ISSUE THREAD

**Issue by Oscar-nesto** [hassio-addons/addon-bookstack#172]
# Problem/Motivation
Home assistant introduced in 2019 ingress option. Several add-ons adapted it and it's great because it forwards the addon page inside the HA instance. It allows seamless experience on a public domain with reverse proxy as well as adding a shortcut into the sidebar panel and much more.

Old addons always want to open the UI with port associated. This will break the functionality of the addon if the user has nginx proxy and does not want to expose ports from the local home network to the public internet. I can configure proxy myself as an alias for the site:port addon wants to open, but it will still maintain a bad user experience because the Open UI button on the addon is hardcoded to broken URL anyways. It does prevent adding the addon shortcut into the left sidebar. 

## Expected behaviour

Click on the Open UI button on the addon card. Opens the addon via HA ingress instead of new tab with URL and port

## Actual behaviour

just uses the domain:port it currently runs on.

## Proposed changes

Documentation for add-on developers describes the details: https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/#for-add-on-developers

**Comment by ssddanbrown** [comment]
I'm not too familiar with ingress and home assistant hosting in general but looks like this has already been raised and addressed in #2, #135 and #141?

**Comment by sinclairpaul** [comment]
@ssddanbrown Ingress is essentially a reverse proxy (via the HA supervisor layer), unfortunately to support it we would need full relative pathing via a subfolder (so that the app can be loaded via Ingress, or the exposed port, assuming not to break existing users).  From the last time I checked I think the attachment path is stored?, which would likely cause issues.

To come back to the original issue, I looked at it originally, and there are challenges implementing.

**Comment by ssddanbrown** [comment]
I'd imagine image/link reference in page content, upon images and some other settings will be the problem, since we store absolute URLs in the database. There is a helper command to update from one url to another but could be risky automating use of that (On every startup for example), only intended to be ran on the rare occasion of moving to a new host/URL.

**Comment by sinclairpaul** [comment]
The challenge we have is that a lot of users will use mDNS names internally (i.e. homeassistant.local) then a different name externally.   I could look at making the addon ingress only, though we won't know the DNS name being accessed, which then becomes a challenge.
